# Generated by Django 2.1.8 on 2019-04-13 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={},
        ),
    ]
